#ifndef _ANYKA_INTERNAL_ERROR_H_
#define _ANYKA_INTERNAL_ERROR_H_

enum ak_error_type {
	ERROR_TYPE_NO_ERROR = 0x00,
	ERROR_TYPE_POINTER_NULL,
	ERROR_TYPE_INVALID_ARG,
	ERROR_TYPE_MALLOC_FAILED,
	ERROR_TYPE_PMEM_MALLOC_FAILED,
	ERROR_TYPE_FUNC_NOT_SUPPORT,		//5
	ERROR_TYPE_NOT_INIT,
	ERROR_TYPE_CALL_ORDER_WRONG,
	ERROR_TYPE_DEV_OPEN_FAILED,
	ERROR_TYPE_DEV_INIT_FAILED,
	ERROR_TYPE_DEV_CTRL_FAILED,			//10
	ERROR_TYPE_DEV_READ_FAILED,
	ERROR_TYPE_DEV_WRITE_FAILED,
	ERROR_TYPE_FILE_OPEN_FAILED,
	ERROR_TYPE_FCNTL_FAILED,
	ERROR_TYPE_FILE_READ_FAILED,		//15
	ERROR_TYPE_FILE_WRITE_FAILED,
	ERROR_TYPE_IOCTL_FAILED,
	ERROR_TYPE_GET_V4L2_PTR_FAILED,
	ERROR_TYPE_INVALID_USER,
	ERROR_TYPE_THREAD_CREATE_FAILED,	//20
	ERROR_TYPE_POPEN_FAILED,
	ERROR_TYPE_MEDIA_LIB_FAILED,
	ERROR_TYPE_NO_DATA,
	ERROR_TYPE_EBUSY,
	ERROR_TYPE_FILE_NOT_EXIT,		//25
	ERROR_TYPE_NUM
};

/** set_error_no - set current errno no.
 * @error_no[IN]: appointed error no.
 * return: none
 * note: internal use interface
 */
void set_error_no(enum ak_error_type error_no);

#endif
