include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += portable
LOCAL_SRCS      += tasks.c
LOCAL_SRCS      += queue.c
LOCAL_SRCS      += list.c
LOCAL_SRCS      += timers.c
LOCAL_SRCS      += event_groups.c
LOCAL_ASMS	+=

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

