include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += turismo.c
LOCAL_ASMS	+= vector_32ivic.S

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

