ifeq (0,$(MAKELEVEL))
TOPDIR := $(CURDIR)/..
export TOPDIR
endif

include $(TOPDIR)/config.mk

INCLUDE         +=
#SRC_DIRS        += bh
SRC_DIRS	+= turismo
LOCAL_SRCS      +=
LOCAL_ASMS	+=

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

