/**@file arch_pwm.h
 * @brief list pwm interface operations
 *
 * PWM is a square wave whose duty cycle and frequency can be adjusted.
 * In AK system, it is generated by a defined gpio and commonly used to adjust backlight of lcd
 * Copyright (C) 2004 Anyka (GuangZhou) Software Technology Co., Ltd.
 * @author  liao_zhijun
 * @date 2010-07-28
 */
#ifndef _PWM_H_
#define _PWM_H_

/** @defgroup PWM PWM group
 * ingroup Drv_Lib
 */
/*@{*/

/**
 * @brief PWM port define
 *  define port name with port number
 */
typedef enum
{
    uiPWM1 = 0,
    uiPWM2,
    uiPWM3,
    uiPWM4,
    uiPWM5,
    MAX_PWM_NUM /* PWM number */
} T_PWM_ID;


/**
 * @brief   set duty cycle of pwm by id, just use in ak8801 or ak8802 chip 
 *
 * @author liao_zhijun
 * @date 2010_07-28
 * @param   [in] pwm_id pwm id
 * @param   [in] pwm_freq frequency of pwm, must in [92HZ--6MHZ] 
 * @param   [in] duty_cycle duty_cycle of pwm
 * @return  bool
 * @retval  true set successfully
 * @retval  false set unsuccessfully
 */
bool pwm_set_duty_cycle(T_PWM_ID pwm_id, unsigned long pwm_freq, unsigned short duty_cycle);

/**
 * @brief  get duty cycle of pwm by id, just use in ak8801 or ak8802 chip 
 *
 * @author liao_zhijun
 * @date 2010_07-28
 * @param   [in] pwm_id pwm id
 * @return  unsigned short duty cycle
 */
unsigned short pwm_get_duty_cycle(T_PWM_ID pwm_id);

/**
 * @brief  get freq of pwm by id, just use in ak8801 or ak8802 chip 
 *
 * @author liao_zhijun
 * @date 2010_07-28
 * @param   [in] pwm_id pwm id
 * @return  unsigned long freq
 */
unsigned long pwm_get_freq(T_PWM_ID pwm_id);


/*@}*/
#endif //_PWM_H_
