include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += turismo
SRC_DIRS	+= CPU_DEF
LOCAL_SRCS      += bsp.c
LOCAL_ASMS	+= start.S

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

