ifeq (0,$(MAKELEVEL))
TOPDIR := $(CURDIR)/../../..
export TOPDIR
endif

include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += ssv_lib.c
//LOCAL_SRCS	+= lib-impl.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

