ifeq (0,$(MAKELEVEL))
TOPDIR := $(CURDIR)/../..
export TOPDIR
endif

include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += bh.c
LOCAL_ASMS	+=

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

