// -----------------------------------------------------------------------------
// 2017-10-18 11:14:44
// -----------------------------------------------------------------------------
// GIT SHA1: d4bd94485311dd1b59cc1bb8e262636651fff4ea
// -----------------------------------------------------------------------------
#include <regs/turismo_v0p5_reg.h>

#define BANK_COUNT 61
static const u32 BASE_BANK_SSV6200[] = {
 FBUS_DMAC_REG_BASE     , // 0 
 SBUS_DMAC_REG_BASE     , // 1 
 I2S_TRX_REG_BASE       , // 2 
 I2CMST_REG_BASE        , // 3 
 SPIMST_REG_BASE        , // 4 
 SYS_REG_BASE           , // 5 
 CSR_ALLON_BASE         , // 6 
 TU0_US_REG_BASE        , // 7 
 TU1_US_REG_BASE        , // 8 
 TU2_US_REG_BASE        , // 9 
 TU3_US_REG_BASE        , // 10
 TM0_MS_REG_BASE        , // 11
 TM1_MS_REG_BASE        , // 12
 TM2_MS_REG_BASE        , // 13
 TM3_MS_REG_BASE        , // 14
 MCU_WDT_REG_BASE       , // 15
 SYS_WDT_REG_BASE       , // 16
 PWM_REG_BASE           , // 17
 IO_REG_BASE            , // 18
 CSR_I2C_SLV_BASE       , // 19
 SD_REG_BASE            , // 20
 SPI_REG_BASE           , // 21
 CSR_I2C_MST_BASE       , // 22
 UART_REG_BASE          , // 23
 DAT_UART_REG_BASE      , // 24
 FLASH_SPI_REG_BASE     , // 25
 DMA_REG_BASE           , // 26
 D2_DMA_REG_BASE        , // 27
 INT_CTRL_REG_BASE      , // 28
 SYS_UTILS_BASE         , // 29
 RTC_MISC_REG_BASE      , // 30
 HCI_REG_BASE           , // 31
 CO_REG_BASE            , // 32
 EFS_REG_BASE           , // 33
 CSR_SPIMAS_BASE        , // 34
 SPIMAS_TX_BUF_BASE     , // 35
 SPIMAS_RX_BUF_BASE     , // 36
 MRX_REG_BASE           , // 37
 AMPDU_REG_BASE         , // 38
 MT_REG_CSR_BASE        , // 39
 TXQ0_MT_Q_REG_CSR_BASE , // 40
 TXQ1_MT_Q_REG_CSR_BASE , // 41
 TXQ2_MT_Q_REG_CSR_BASE , // 42
 TXQ3_MT_Q_REG_CSR_BASE , // 43
 TXQ4_MT_Q_REG_CSR_BASE , // 44
 TXQ5_MT_Q_REG_CSR_BASE , // 45
 MT_RESPFRM_REG_BASE    , // 46
 HIF_INFO_BASE          , // 47
 PHY_RATE_INFO_BASE     , // 48
 MAC_GLB_SET_BASE       , // 49
 BTCX_REG_BASE          , // 50
 MIB_REG_BASE           , // 51
 WSID_EXT_BASE          , // 52
 RF_REG_BASE            , // 53
 CSR_TU_RF_BASE         , // 54
 CSR_TU_PMU_BASE        , // 55
 CSR_TU_PHY_BASE        , // 56
 MB_REG_BASE            , // 57
 ID_MNG_REG_BASE        , // 58
 MMU_REG_BASE           , // 59
 CSR_TEMP_REG_BASE      , // 60
 0x00000000
};
static const char* STR_BANK_SSV6200[] = {
 "FBUS_DMAC_REG"     , // 0 
 "SBUS_DMAC_REG"     , // 1 
 "I2S_TRX_REG"       , // 2 
 "I2CMST_REG"        , // 3 
 "SPIMST_REG"        , // 4 
 "SYS_REG"           , // 5 
 "CSR_ALLON"         , // 6 
 "TU0_US_REG"        , // 7 
 "TU1_US_REG"        , // 8 
 "TU2_US_REG"        , // 9 
 "TU3_US_REG"        , // 10
 "TM0_MS_REG"        , // 11
 "TM1_MS_REG"        , // 12
 "TM2_MS_REG"        , // 13
 "TM3_MS_REG"        , // 14
 "MCU_WDT_REG"       , // 15
 "SYS_WDT_REG"       , // 16
 "PWM_REG"           , // 17
 "IO_REG"            , // 18
 "CSR_I2C_SLV"       , // 19
 "SD_REG"            , // 20
 "SPI_REG"           , // 21
 "CSR_I2C_MST"       , // 22
 "UART_REG"          , // 23
 "DAT_UART_REG"      , // 24
 "FLASH_SPI_REG"     , // 25
 "DMA_REG"           , // 26
 "D2_DMA_REG"        , // 27
 "INT_CTRL_REG"      , // 28
 "SYS_UTILS"         , // 29
 "RTC_MISC_REG"      , // 30
 "HCI_REG"           , // 31
 "CO_REG"            , // 32
 "EFS_REG"           , // 33
 "CSR_SPIMAS"        , // 34
 "SPIMAS_TX_BUF"     , // 35
 "SPIMAS_RX_BUF"     , // 36
 "MRX_REG"           , // 37
 "AMPDU_REG"         , // 38
 "MT_REG_CSR"        , // 39
 "TXQ0_MT_Q_REG_CSR" , // 40
 "TXQ1_MT_Q_REG_CSR" , // 41
 "TXQ2_MT_Q_REG_CSR" , // 42
 "TXQ3_MT_Q_REG_CSR" , // 43
 "TXQ4_MT_Q_REG_CSR" , // 44
 "TXQ5_MT_Q_REG_CSR" , // 45
 "MT_RESPFRM_REG"    , // 46
 "HIF_INFO"          , // 47
 "PHY_RATE_INFO"     , // 48
 "MAC_GLB_SET"       , // 49
 "BTCX_REG"          , // 50
 "MIB_REG"           , // 51
 "WSID_EXT"          , // 52
 "RF_REG"            , // 53
 "CSR_TU_RF"         , // 54
 "CSR_TU_PMU"        , // 55
 "CSR_TU_PHY"        , // 56
 "MB_REG"            , // 57
 "ID_MNG_REG"        , // 58
 "MMU_REG"           , // 59
 "CSR_TEMP_REG"      , // 60
 ""
};
static const u32 SIZE_BANK_SSV6200[] = {
 FBUS_DMAC_REG_BANK_SIZE     , // 0 
 SBUS_DMAC_REG_BANK_SIZE     , // 1 
 I2S_TRX_REG_BANK_SIZE       , // 2 
 I2CMST_REG_BANK_SIZE        , // 3 
 SPIMST_REG_BANK_SIZE        , // 4 
 SYS_REG_BANK_SIZE           , // 5 
 CSR_ALLON_BANK_SIZE         , // 6 
 TU0_US_REG_BANK_SIZE        , // 7 
 TU1_US_REG_BANK_SIZE        , // 8 
 TU2_US_REG_BANK_SIZE        , // 9 
 TU3_US_REG_BANK_SIZE        , // 10
 TM0_MS_REG_BANK_SIZE        , // 11
 TM1_MS_REG_BANK_SIZE        , // 12
 TM2_MS_REG_BANK_SIZE        , // 13
 TM3_MS_REG_BANK_SIZE        , // 14
 MCU_WDT_REG_BANK_SIZE       , // 15
 SYS_WDT_REG_BANK_SIZE       , // 16
 PWM_REG_BANK_SIZE           , // 17
 IO_REG_BANK_SIZE            , // 18
 CSR_I2C_SLV_BANK_SIZE       , // 19
 SD_REG_BANK_SIZE            , // 20
 SPI_REG_BANK_SIZE           , // 21
 CSR_I2C_MST_BANK_SIZE       , // 22
 UART_REG_BANK_SIZE          , // 23
 DAT_UART_REG_BANK_SIZE      , // 24
 FLASH_SPI_REG_BANK_SIZE     , // 25
 DMA_REG_BANK_SIZE           , // 26
 D2_DMA_REG_BANK_SIZE        , // 27
 INT_CTRL_REG_BANK_SIZE      , // 28
 SYS_UTILS_BANK_SIZE         , // 29
 RTC_MISC_REG_BANK_SIZE      , // 30
 HCI_REG_BANK_SIZE           , // 31
 CO_REG_BANK_SIZE            , // 32
 EFS_REG_BANK_SIZE           , // 33
 CSR_SPIMAS_BANK_SIZE        , // 34
 SPIMAS_TX_BUF_BANK_SIZE     , // 35
 SPIMAS_RX_BUF_BANK_SIZE     , // 36
 MRX_REG_BANK_SIZE           , // 37
 AMPDU_REG_BANK_SIZE         , // 38
 MT_REG_CSR_BANK_SIZE        , // 39
 TXQ0_MT_Q_REG_CSR_BANK_SIZE , // 40
 TXQ1_MT_Q_REG_CSR_BANK_SIZE , // 41
 TXQ2_MT_Q_REG_CSR_BANK_SIZE , // 42
 TXQ3_MT_Q_REG_CSR_BANK_SIZE , // 43
 TXQ4_MT_Q_REG_CSR_BANK_SIZE , // 44
 TXQ5_MT_Q_REG_CSR_BANK_SIZE , // 45
 MT_RESPFRM_REG_BANK_SIZE    , // 46
 HIF_INFO_BANK_SIZE          , // 47
 PHY_RATE_INFO_BANK_SIZE     , // 48
 MAC_GLB_SET_BANK_SIZE       , // 49
 BTCX_REG_BANK_SIZE          , // 50
 MIB_REG_BANK_SIZE           , // 51
 WSID_EXT_BANK_SIZE          , // 52
 RF_REG_BANK_SIZE            , // 53
 CSR_TU_RF_BANK_SIZE         , // 54
 CSR_TU_PMU_BANK_SIZE        , // 55
 CSR_TU_PHY_BANK_SIZE        , // 56
 MB_REG_BANK_SIZE            , // 57
 ID_MNG_REG_BANK_SIZE        , // 58
 MMU_REG_BANK_SIZE           , // 59
 CSR_TEMP_REG_BANK_SIZE      , // 60
 0x00000000
};
