include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS	+=
LOCAL_SRCS      += memcpy.c
LOCAL_SRCS      += memmove.c
LOCAL_SRCS      += memset.c
LOCAL_SRCS      += strcat.c
LOCAL_SRCS      += strcasecmp.c
LOCAL_SRCS	+= strcmp.c
LOCAL_SRCS	+= strcpy.c
LOCAL_SRCS	+= strdup.c
LOCAL_SRCS	+= strlen.c
LOCAL_SRCS	+= strstr.c
LOCAL_SRCS	+= strupr.c
LOCAL_SRCS	+= wchar.c
LOCAL_ASMS	+=

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

