# cloud platform or protocol config
CONFIG_DANA_SUPPORT = n
CONFIG_RTSP_SUPPORT = y

# WIFI support config
CONFIG_WIFI_RTL8188EUS = y
CONFIG_WIFI_RTL8188FTV = n
CONFIG_WIFI_RTL8189ETV = n
CONFIG_WIFI_RTL8189FTV = n
CONFIG_WIFI_SSV6X5X = n
CONFIG_WIFI_ATBM603X = n
CONFIG_WIFI_HI3881 = n

# Other config
CONFIG_WATCHDOG_ENABLE = y
CONFIG_UTILS_SUPPORT = n
