include $(TOPDIR)/config.mk

INCLUDE         += $(CURDIR)/../../freertos
SRC_DIRS        +=
LOCAL_SRCS      += rtos_wrapper.c
LOCAL_ASMS	+=

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

