include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      +=
LOCAL_ASMS	+= os_cpu_a.S

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

