include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += Source
LOCAL_SRCS      +=
LOCAL_ASMS	+=

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

