include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += kernel
SRC_DIRS	+= hal
SRC_DIRS	+= nds32
SRC_DIRS	+= serial
LOCAL_SRCS      += portISR.c
LOCAL_SRCS      += port.c
#LOCAL_SRCS      += rtos_wrapper.c
LOCAL_ASMS	+=

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

