include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += stdio
SRC_DIRS        += string
SRC_DIRS        += stdlib
LOCAL_SRCS      +=
LOCAL_ASMS	+=

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

