/*
 * Copyright (c) 2014 South Silicon Valley Microelectronics Inc.
 * Copyright (c) 2015 iComm Semiconductor Ltd.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef _SSV6XXX_NETLINK_CORE_H_
#define _SSV6XXX_NETLINK_CORE_H_

struct ssv_wireless_register {
	u32	address;
	u32	value;
};

/* DEFINE SSV WIRELESS NETLINK ATTRIBUTE */
enum {
	SSV_WIRELESS_ATTR_UNSPEC,
	SSV_WIRELESS_ATTR_CONFIG,
	SSV_WIRELESS_ATTR_REGISTER,
	SSV_WIRELESS_ATTR_TXFRAME,
	SSV_WIRELESS_ATTR_RXFRAME,
	SSV_WIRELESS_ATTR_START_HCI,
	SSV_WIRELESS_ATTR_TEST,
	__SSV_WIRELESS_ATTR_MAX,
};
#define SSV_WIRELESS_ATTR_MAX (__SSV_WIRELESS_ATTR_MAX - 1)

/* DEFINE SSV WIRELESS NETLINK COMMAND */
enum {
	SSV_WIRELESS_CMD_UNSPEC,
	SSV_WIRELESS_CMD_CONFIG,
	SSV_WIRELESS_CMD_READ_REG,
	SSV_WIRELESS_CMD_WRITE_REG,
	SSV_WIRELESS_CMD_TXFRAME,
	SSV_WIRELESS_CMD_RXFRAME,
	SSV_WIRELESS_CMD_START_HCI,
	SSV_WIRELESS_CMD_TEST,
	__SSV_WIRELESS_CMD_MAX,
};
#define SSV_WIRELESS_CMD_MAX (__SSV_WIRELESS_CMD_MAX - 1)

#endif
