include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS	+=
LOCAL_SRCS      += serial.c
LOCAL_ASMS	+=

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

