include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += 
LOCAL_SRCS      += drv_uart.c

.depend: $(LOCAL_SRCS) $(LOCAL_ASMS)

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

