include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS	+=
LOCAL_SRCS      += fgets.c
LOCAL_SRCS      += fputs.c
LOCAL_SRCS      += fprintf.c
LOCAL_SRCS      += do_printf.c
LOCAL_SRCS      += printf.c
LOCAL_ASMS	+=

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

